name: GitHub Bounties

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours

jobs:
  fetch-bounties:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
        
    - name: Install Dependencies
      run: npm install
        
    - name: Fetch Bounties
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: node github-bounties.js 