name: Lint and Test

on: [push]

env:
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  TWITTER_EMAIL: ${{ secrets.TWITTER_EMAIL }}
  TWITTER_USERNAME: ${{ secrets.TWITTER_USERNAME }}
  TWITTER_PASSWORD: ${{ secrets.TWITTER_PASSWORD }}
  DISCORD_API_TOKEN: ${{ secrets.DISCORD_API_TOKEN }}
  ELEVENLABS_API_KEY: ${{ secrets.ELEVENLABS_API_KEY }}
  ELEVENLABS_VOICE: ${{ secrets.ELEVENLABS_VOICE }}
  ELEVENLABS_MODEL: ${{ secrets.ELEVENLABS_MODEL }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r requirements.txt
    - name: Running tests
      run: |
        pytest test.py
